# .github/workflows/cron.yml
name: Trigger Cron Jobs

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  trigger-schedule-bots:
    runs-on: ubuntu-latest
    steps:
      - name: Call schedule-bots endpoint
        run: |
          curl --request GET \
          --url '${{ secrets.DEPLOYMENT_URL }}/api/schedule-bots' \
          --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'